### PR TITLE
Always exit with errors when comparison failed

### PR DESCRIPTION
**Pull request by alexandcote**
First, thanks a lot for your lib 👍 

We would like to use your lib into our linter. 
The task have to run all comparaison and fail at the end if an error was found.
I add a new flag to print only errors.

Let me know if you have any recommendation.

Thanks

### CODE REVIEW

**Comment by nielskrijger** [comment]
Thanks Alexandre for the PR

Your use case makes sense. I'll review the PR Monday the latest and publish a new version soon afterwards if accepted.

**Comment by alexandcote** [comment]
Perfect 👍 
Thanks

**Comment by nielskrijger** [comment]
Hi Alexandcode,

I accepted the PR with a few changes. 

It felt like the behaviour you wanted should have been the default rather than an additional option. I removed the `--only-errors` flag but kept the other changes you made apart from one; depending on the `--only-errors` you'd either print or not print a certain `output(...)`-statement. The `--only-errors` flag does not describe that behaviour properly, so if you want to reintroduce that with a different option name?

I don't know why you wanted to make that specific `output(...)` optional so I wasn't able to come up with a good name.

I published an 0.3.0 version so you can give it a try.

Thanks again

**Comment by alexandcote** [comment]
Thanks a lot ! 👍

**Pull request merged**
